/* Auto-generated by genmsg_cpp for file /home/aqua/rospkg/ros_opentld/tld_msgs/msg/BoundingBox.msg */
#ifndef TLD_MSGS_MESSAGE_BOUNDINGBOX_H
#define TLD_MSGS_MESSAGE_BOUNDINGBOX_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace tld_msgs
{
template <class ContainerAllocator>
struct BoundingBox_ {
  typedef BoundingBox_<ContainerAllocator> Type;

  BoundingBox_()
  : header()
  , x(0)
  , y(0)
  , width(0)
  , height(0)
  , confidence(0.0)
  {
  }

  BoundingBox_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , x(0)
  , y(0)
  , width(0)
  , height(0)
  , confidence(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef int32_t _x_type;
  int32_t x;

  typedef int32_t _y_type;
  int32_t y;

  typedef int32_t _width_type;
  int32_t width;

  typedef int32_t _height_type;
  int32_t height;

  typedef float _confidence_type;
  float confidence;


  typedef boost::shared_ptr< ::tld_msgs::BoundingBox_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tld_msgs::BoundingBox_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct BoundingBox
typedef  ::tld_msgs::BoundingBox_<std::allocator<void> > BoundingBox;

typedef boost::shared_ptr< ::tld_msgs::BoundingBox> BoundingBoxPtr;
typedef boost::shared_ptr< ::tld_msgs::BoundingBox const> BoundingBoxConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::tld_msgs::BoundingBox_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::tld_msgs::BoundingBox_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace tld_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::tld_msgs::BoundingBox_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::tld_msgs::BoundingBox_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::tld_msgs::BoundingBox_<ContainerAllocator> > {
  static const char* value() 
  {
    return "21805e65f91af60e9268e4d1a43ded1e";
  }

  static const char* value(const  ::tld_msgs::BoundingBox_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x21805e65f91af60eULL;
  static const uint64_t static_value2 = 0x9268e4d1a43ded1eULL;
};

template<class ContainerAllocator>
struct DataType< ::tld_msgs::BoundingBox_<ContainerAllocator> > {
  static const char* value() 
  {
    return "tld_msgs/BoundingBox";
  }

  static const char* value(const  ::tld_msgs::BoundingBox_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::tld_msgs::BoundingBox_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
int32 x\n\
int32 y\n\
int32 width\n\
int32 height\n\
float32 confidence\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::tld_msgs::BoundingBox_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::tld_msgs::BoundingBox_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::tld_msgs::BoundingBox_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::tld_msgs::BoundingBox_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.x);
    stream.next(m.y);
    stream.next(m.width);
    stream.next(m.height);
    stream.next(m.confidence);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct BoundingBox_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tld_msgs::BoundingBox_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::tld_msgs::BoundingBox_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y);
    s << indent << "width: ";
    Printer<int32_t>::stream(s, indent + "  ", v.width);
    s << indent << "height: ";
    Printer<int32_t>::stream(s, indent + "  ", v.height);
    s << indent << "confidence: ";
    Printer<float>::stream(s, indent + "  ", v.confidence);
  }
};


} // namespace message_operations
} // namespace ros

#endif // TLD_MSGS_MESSAGE_BOUNDINGBOX_H

