/* Auto-generated by genmsg_cpp for file /home/aqua/rospkg/ros_opentld/tld_msgs/msg/Target.msg */
#ifndef TLD_MSGS_MESSAGE_TARGET_H
#define TLD_MSGS_MESSAGE_TARGET_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "tld_msgs/BoundingBox.h"
#include "sensor_msgs/Image.h"

namespace tld_msgs
{
template <class ContainerAllocator>
struct Target_ {
  typedef Target_<ContainerAllocator> Type;

  Target_()
  : bb()
  , img()
  {
  }

  Target_(const ContainerAllocator& _alloc)
  : bb(_alloc)
  , img(_alloc)
  {
  }

  typedef  ::tld_msgs::BoundingBox_<ContainerAllocator>  _bb_type;
   ::tld_msgs::BoundingBox_<ContainerAllocator>  bb;

  typedef  ::sensor_msgs::Image_<ContainerAllocator>  _img_type;
   ::sensor_msgs::Image_<ContainerAllocator>  img;


  typedef boost::shared_ptr< ::tld_msgs::Target_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tld_msgs::Target_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Target
typedef  ::tld_msgs::Target_<std::allocator<void> > Target;

typedef boost::shared_ptr< ::tld_msgs::Target> TargetPtr;
typedef boost::shared_ptr< ::tld_msgs::Target const> TargetConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::tld_msgs::Target_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::tld_msgs::Target_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace tld_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::tld_msgs::Target_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::tld_msgs::Target_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::tld_msgs::Target_<ContainerAllocator> > {
  static const char* value() 
  {
    return "af750259f2bd9aed12064a11baa3c3c2";
  }

  static const char* value(const  ::tld_msgs::Target_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xaf750259f2bd9aedULL;
  static const uint64_t static_value2 = 0x12064a11baa3c3c2ULL;
};

template<class ContainerAllocator>
struct DataType< ::tld_msgs::Target_<ContainerAllocator> > {
  static const char* value() 
  {
    return "tld_msgs/Target";
  }

  static const char* value(const  ::tld_msgs::Target_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::tld_msgs::Target_<ContainerAllocator> > {
  static const char* value() 
  {
    return "BoundingBox bb\n\
sensor_msgs/Image img\n\
\n\
================================================================================\n\
MSG: tld_msgs/BoundingBox\n\
Header header\n\
int32 x\n\
int32 y\n\
int32 width\n\
int32 height\n\
float32 confidence\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: sensor_msgs/Image\n\
# This message contains an uncompressed image\n\
# (0, 0) is at top-left corner of image\n\
#\n\
\n\
Header header        # Header timestamp should be acquisition time of image\n\
                     # Header frame_id should be optical frame of camera\n\
                     # origin of frame should be optical center of cameara\n\
                     # +x should point to the right in the image\n\
                     # +y should point down in the image\n\
                     # +z should point into to plane of the image\n\
                     # If the frame_id here and the frame_id of the CameraInfo\n\
                     # message associated with the image conflict\n\
                     # the behavior is undefined\n\
\n\
uint32 height         # image height, that is, number of rows\n\
uint32 width          # image width, that is, number of columns\n\
\n\
# The legal values for encoding are in file src/image_encodings.cpp\n\
# If you want to standardize a new string format, join\n\
# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n\
\n\
string encoding       # Encoding of pixels -- channel meaning, ordering, size\n\
                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n\
\n\
uint8 is_bigendian    # is this data bigendian?\n\
uint32 step           # Full row length in bytes\n\
uint8[] data          # actual matrix data, size is (step * rows)\n\
\n\
";
  }

  static const char* value(const  ::tld_msgs::Target_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::tld_msgs::Target_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.bb);
    stream.next(m.img);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Target_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tld_msgs::Target_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::tld_msgs::Target_<ContainerAllocator> & v) 
  {
    s << indent << "bb: ";
s << std::endl;
    Printer< ::tld_msgs::BoundingBox_<ContainerAllocator> >::stream(s, indent + "  ", v.bb);
    s << indent << "img: ";
s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.img);
  }
};


} // namespace message_operations
} // namespace ros

#endif // TLD_MSGS_MESSAGE_TARGET_H

